// <auto-generated />
using System;
using Assignment_1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment_1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240223143308_Hotels")]
    partial class Hotels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Assignment_1.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Destination")
                        .HasColumnType("longtext");

                    b.Property<string>("FlightNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Origin")
                        .HasColumnType("longtext");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalTime = new DateTime(2024, 2, 23, 11, 33, 8, 753, DateTimeKind.Local).AddTicks(8660),
                            DepartureTime = new DateTime(2024, 2, 23, 9, 33, 8, 753, DateTimeKind.Local).AddTicks(8620),
                            Destination = "City B",
                            FlightNumber = "ABC123",
                            Origin = "City A",
                            Price = 200f
                        },
                        new
                        {
                            Id = 2,
                            ArrivalTime = new DateTime(2024, 2, 23, 14, 33, 8, 753, DateTimeKind.Local).AddTicks(8670),
                            DepartureTime = new DateTime(2024, 2, 23, 12, 33, 8, 753, DateTimeKind.Local).AddTicks(8670),
                            Destination = "City C",
                            FlightNumber = "DEF456",
                            Origin = "City B",
                            Price = 250f
                        });
                });

            modelBuilder.Entity("Assignment_1.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true,
                            Location = "City X",
                            Name = "Hotel ABC",
                            PricePerNight = 150m,
                            Rating = 4
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = true,
                            Location = "City Y",
                            Name = "Hotel XYZ",
                            PricePerNight = 120m,
                            Rating = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
